CREATE TABLE IF NOT EXISTS clase_accesorios(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL CHECK (nombre <>'')
);

CREATE TABLE IF NOT EXISTS subclase_accesorios(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL CHECK (nombre <>''),
    clase_accesorio_id INTEGER NOT NULL REFERENCES clase_accesorios(id)
);

CREATE TABLE IF NOT EXISTS tareas (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    descripcion TEXT NOT NULL CHECK (descripcion <>''),
    subclase_accesorio_id INTEGER NOT NULL REFERENCES subclase_accesorios(id),
    fecha_inicio DATE,
    fecha_fin DATE
);

